version: '3.7'
services:
    auth-postgres:
        image: postgres:alpine
        container_name: auth-postgres
        restart: always
        env_file:
            - ./config/db.env
        ports:
            - 5432:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data
    session-redis:
        image: redis:alpine
        container_name: session-redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./redis_data:/data
    nginx: 
      image: nginx:latest
      container_name: nginx
      volumes:
        - ./config/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx-logs:/etc/nginx/logs/
        - ./build/client/:/etc/nginx/html/
      ports:
        - 8502:80
    haproxy:
      image: haproxy
      container_name: haproxy-proxy
      restart: unless-stopped
    #   network_mode: "host" # DO NOT USE ON MAC!    Required when running on Linux hosts.
      ports:
          - 443:443
          - 80:80
      volumes:
          - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
          - ./certs:/etc/ssl/
