version: '3.7'
services:
    auth-postgres:
        image: postgres:alpine
        container_name: auth-postgres
        restart: always
        env_file:
            - db.env
        ports:
            - "5432:5432"
        volumes:
            - ./db_data:/var/lib/postgresql/data
    # game-redis:
    #     image: redis:alpine
    #     container_name: game-redis
    #     restart: always
    #     ports:
    #         - 6379:6379
    #     volumes:
    #         - ./redis_data:/data